// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package repo

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Menu struct {
	ID          uuid.UUID   `json:"id"`
	Category    string      `json:"category"`
	MenuItemIds []uuid.UUID `json:"menu_item_ids"`
}

type Menuitem struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Price    int32     `json:"price"`
	ImageUrl string    `json:"image_url"`
	MenuID   uuid.UUID `json:"menu_id"`
}

type Order struct {
	ID          uuid.UUID             `json:"id"`
	TableID     uuid.UUID             `json:"table_id"`
	Amount      sql.NullInt32         `json:"amount"`
	OrderItems  pqtype.NullRawMessage `json:"order_items"`
	CreatedAt   time.Time             `json:"created_at"`
	DeliveredAt sql.NullTime          `json:"delivered_at"`
}

type Table struct {
	ID          uuid.UUID   `json:"id"`
	TableNumber int32       `json:"table_number"`
	OrderIds    []uuid.UUID `json:"order_ids"`
}

type User struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	Name        string    `json:"name"`
	PhoneNumber string    `json:"phone_number"`
	Password    string    `json:"password"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
